name: gym_buddy
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  go_router: ^16.2.1
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  freezed: ^3.2.3
  build_runner: ^2.7.1
  flutter_screenutil: ^5.9.3
  phone_text_field: ^2.0.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  json_serializable: ^6.11.1
  dartz: ^0.10.1
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  talker: ^5.0.0
  talker_flutter: ^5.0.0
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.2.1
  swipe_to: ^1.0.6
  image_picker: ^1.2.0
  firebase_storage: ^13.0.2
  solid_lints: ^0.3.1
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  lottie: ^3.3.2
  easy_localization: ^3.0.8
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  



flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/lottie/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 